#! /bin/sh
set -e

if [ -f /usr/lib/libreoffice/program/intro.png.divert ]; then
  rm -f /usr/lib/libreoffice/program/intro.png
  dpkg-divert --remove --rename /usr/lib/libreoffice/program/intro.png
fi
if [ -f /usr/lib/libreoffice/program/about.png.divert ]; then
  rm -f /usr/lib/libreoffice/program/about.png
  dpkg-divert --remove --rename /usr/lib/libreoffice/program/about.png
fi
if [ -f /etc/libreoffice/sofficerc.divert ]; then
  rm -f /etc/libreoffice/sofficerc
  dpkg-divert --remove --rename /etc/libreoffice/sofficerc
fi
