#! /bin/sh
set -e

if [ -f /etc/issue.divert ]; then
  rm -f /etc/issue
  dpkg-divert --remove --rename /etc/issue
fi
if [ -f /etc/issue.net.divert ]; then
  rm -f /etc/issue.net
  dpkg-divert --remove --rename /etc/issue.net
fi
if [ -f /etc/lsb-release.divert ]; then
  rm -f /etc/lsb-release
  dpkg-divert --remove --rename /etc/lsb-release
fi
if [ -f /etc/motd.divert ]; then
  rm -f /etc/motd
  dpkg-divert --remove --rename /etc/motd
fi
