#! /bin/sh
set -e

case "$1" in
  configure)
  if [ -f /usr/share/gnome-control-center/ui/GnomeLogoVerticalMedium.svg ]; then
    dpkg-divert --add --local --divert /usr/share/gnome-control-center/ui/GnomeLogoVerticalMedium.svg.divert --rename /usr/share/gnome-control-center/ui/GnomeLogoVerticalMedium.svg
    cp -a /usr/share/gnome-control-center/ui/OI_BlankOn.svg /usr/share/gnome-control-center/ui/GnomeLogoVerticalMedium.svg
  fi
esac

exit 0
