#! /bin/sh
set -e

case "$1" in
  configure)
  if [ -f /usr/share/system-config-printer/testpage-a4.ps ]; then
    dpkg-divert --add --local --divert /usr/share/system-config-printer/testpage-a4.ps.divert --rename /usr/share/system-config-printer/testpage-a4.ps
    cp -a /usr/share/system-config-printer/testpage-blankon-a4.ps /usr/share/system-config-printer/testpage-a4.ps
  fi
  if [ -f /usr/share/system-config-printer/testpage-letter.ps ]; then
    dpkg-divert --add --local --divert /usr/share/system-config-printer/testpage-letter.ps.divert --rename /usr/share/system-config-printer/testpage-letter.ps
    cp -a /usr/share/system-config-printer/testpage-blankon-letter.ps /usr/share/system-config-printer/testpage-letter.ps
  fi
esac

exit 0
