tangerine-icon-theme/16x16/places/start-here-blankon.png /usr/share/icons/Tangerine/16x16/places/
tangerine-icon-theme/22x22/places/start-here-blankon.png /usr/share/icons/Tangerine/22x22/places/
tangerine-icon-theme/24x24/places/start-here-blankon.png /usr/share/icons/Tangerine/24x24/places/
tangerine-icon-theme/48x48/places/start-here-blankon.png /usr/share/icons/Tangerine/48x48/places/
tangerine-icon-theme/scalable/places/start-here-blankon.svg /usr/share/icons/Tangerine/scalable/places/
