#! /bin/sh

set -e

case "$1" in
    configure)

        if ! test -f /etc/apt/trusted.gpg; then
                apt-key add /usr/share/apt/blankon-archive.gpg
                apt-key add /usr/share/apt/ubuntu-archive.gpg
        fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0



