#! /bin/sh
set -e

case "$1" in
  configure)
  if [ -f /usr/share/checkbox/gtk/hwtest-gtk-head.png ]; then
    dpkg-divert --add --local --divert /usr/share/checkbox/gtk/hwtest-gtk-head.png.divert --rename /usr/share/checkbox/gtk/hwtest-gtk-head.png
    cp -a /usr/share/checkbox/gtk/blankon.hwtest-gtk-head.png /usr/share/checkbox/gtk/hwtest-gtk-head.png
  fi
  if [ -f /usr/share/checkbox/gtk/hwtest-gtk.glade ]; then
    dpkg-divert --add --local --divert /usr/share/checkbox/gtk/hwtest-gtk.glade.divert --rename /usr/share/checkbox/gtk/hwtest-gtk.glade
    cp -a /usr/share/checkbox/gtk/blankon.hwtest-gtk.glade /usr/share/checkbox/gtk/hwtest-gtk.glade
  fi
esac

exit 0
