#! /bin/sh
set -e

case "$1" in
  configure)
  if [ -f /usr/share/launchpad-integration/launchpadintegration/urls.py ]; then
    dpkg-divert --add --local --divert /usr/share/launchpad-integration/launchpadintegration/urls.py.divert --rename /usr/share/launchpad-integration/launchpadintegration/urls.py
    cp -a /usr/share/launchpad-integration/launchpadintegration/blankon.urls.py /usr/share/launchpad-integration/launchpadintegration/urls.py
  fi
esac

exit 0
