#! /bin/sh
set -e

case "$1" in
  configure)
  if [ -f /usr/share/icons/Tango/scalable/places/start-here.svg ]; then
    dpkg-divert --add --local --divert /usr/share/icons/Tango/scalable/places/start-here.svg.divert --rename /usr/share/icons/Tango/scalable/places/start-here.svg
    cp -a /usr/share/icons/Tango/scalable/places/start-here-blankon.svg /usr/share/icons/Tango/scalable/places/start-here.svg
  fi
esac

exit 0
